-- WHAT ABOUT THE PARTIAL SEARCH
-- WE USE LIKE AND % (WILD CARD)
--  % can represent 0 or more character of any kind
--  _ can represent exactly one character of any kind
/*

 'D%'--anything that starts with D, David, Dog,Danny
 '%d'-anything that ends with d, dad,kid,bird
 '%d%---anything that contains d.
    Adam, Cassandra, Brandon,Aladdin,
    sid,bid,kid,
    david,danny,dog

    'D%a'--anything that starts with D and ends with a.
     Diana, Donna , Damla , Daria

    'S%e%n'-- -- any start with S end with n
                --and has e something in the middle
    Steven,, Stephen, Selen , Serkan , Sebastian

 'T_'--starts with T and followed by exactly one character of any kind
    Tj , TD , Ta , T! , TV , T2,

 '_a_'-- starts with any one character, followed by a
             and followed by any one character
            Dad , Man , Fat, Tab , Gap , Mad

 Like STATEMENT only works for string(Varchar)
 */

SELECT FIRST_NAME FROM EMPLOYEES
--WHERE FIRST_NAME LIKE 'D%';--9
--WHERE FIRST_NAME LIKE 'Da%';--5
--WHERE FIRST_NAME LIKE '%d'; --6
--WHERE FIRST_NAME LIKE '%d%'; --15
--WHERE FIRST_NAME LIKE 'D%a'; --1
--WHERE FIRST_NAME LIKE 'S%e%n'; --3
--WHERE FIRST_NAME LIKE 'T_';--1
WHERE FIRST_NAME LIKE  '_a_'; --1

SELECT PHONE_NUMBER FROM EMPLOYEES
--WHERE PHONE_NUMBER LIKE '515%';--21 STARTS WITH 515 --21
WHERE PHONE_NUMBER LIKE '%.121.%';--CONTAINS WITH 121--8

-- YOU CAN OPTIONALLY GIVE AN ALIAS( NICKNAME) FOR YOUR COLUMN
-- TO CHANGE THE RESULTING COLUMN NAME (ONLY CHANGING DISPLAY NOT ACTUALLY CHANGING IN DATABASE )
-- USING THE KEYWORD AS RIGHT AFTER COLUMN NAME
-- and PROVIDE NICKNAME Either without " " if single word
-- and USE "" IF MORE THAN ONE WORD   AS "MORE THAN ONE"

-- Display all FIRST_NAME , SALARY in Employees table
-- modify the column name for Salary in result to Money
SELECT FIRST_NAME,SALARY AS MONEY
FROM EMPLOYEES;



-- Display all FIRST_NAME , LAST_NAME in Employees table
-- modify the column name for AS BELOW
-- FIRST_NAME -> GIVEN_NAME    LAST_NAME --> FAMILY_NAME
SELECT FIRST_NAME AS  GIVEN_NAME, LAST_NAME AS  FAMILY_NAME
FROM EMPLOYEES;

-- Display all FIRST_NAME , LAST_NAME in Employees table
-- modify the column name for AS BELOW
-- FIRST_NAME -> GIVEN NAME    LAST_NAME --> FAMILY NAME
SELECT FIRST_NAME AS "GIVEN NAME", LAST_NAME AS "FAMILY NAME"
FROM EMPLOYEES;


-- CONCATENATION IN SQL USE DOUBLE PIPE || (THIS IS NOT OR )
-- DISPLAY FIRST_NAME , LAST_NAME , FULL_NAME FOR EMPLOYEE
SELECT FIRST_NAME, LAST_NAME,
       FIRST_NAME|| ' '|| LAST_NAME AS "FULL_NAME"
FROM EMPLOYEES;

--ARITHMETIC OPERATION:+ - * /
--Display employee name and salary
-- And increased_salary after 5000$ raise

SELECT FIRST_NAME,SALARY,
       SALARY + 5000 AS "Increased_Salary"
From EMPLOYEES;

-- And decreased_salary after 2000$ cut
SELECT FIRST_NAME,SALARY,
       SALARY - 2000 AS "Decreased_Salary"
FROM EMPLOYEES;

--And yearly_salary --Multiply by 12

SELECT FIRST_NAME,SALARY,
       SALARY * 12 AS "Yearly_Salary"
FROM EMPLOYEES;

--And weekly_salary --Divide by 4
SELECT FIRST_NAME,SALARY,
       SALARY/4 AS "Weekly_Salary"
FROM EMPLOYEES;

--in one shot!
SELECT FIRST_NAME,SALARY,
       SALARY + 5000 AS "Increased_Salary",
       SALARY - 2000 AS "Decreased_Salary",
       SALARY * 12 AS "Yearly_Salary",
       SALARY/4 AS "Weekly_Salary"
FROM EMPLOYEES;

--SQL built-in functions:
--Reusable code that wrapped into function for common tasks
--Like rounding numbers,getting length of str and more
--single row function:
    --it affect each and every row and return same number of row

    --Few text functions:
    --Upper: Accept one parameter(column name) and return uppercase
    --Lower: Accept one parameter(column name) and return lowercase
    --Length:Return the length of string

    --Display first_name,
    -- and uppercase, lowercase and length first name
    -- in employee table

SELECT FIRST_NAME,
       UPPER(FIRST_NAME) AS "UPPERCASE_NAME",
       LOWER(FIRST_NAME) AS "LOWERCASE_NAME",
       LENGTH(FIRST_NAME) AS "CHAR_COUNT"
FROM EMPLOYEES;

--FIND OUT ALL FIRST_NAME AND CHARACTER COUNT
--ONLY DISPLAY IF CHARACTER COUNT IS EXACTLY 5
SELECT FIRST_NAME,LENGTH(FIRST_NAME)
FROM EMPLOYEES
WHERE LENGTH(FIRST_NAME) =5;

----ONLY DISPLAY IF FIRST NAME CHARACTER COUNT IS MORE THAN 10
SELECT FIRST_NAME,LENGTH(FIRST_NAME)
FROM EMPLOYEES
WHERE LENGTH(FIRST_NAME) > 10;

----ONLY DISPLAY IF FIRST NAME CHARACTER COUNT BETWEEN 7 -9
SELECT FIRST_NAME,LENGTH(FIRST_NAME)
FROM EMPLOYEES
WHERE LENGTH(FIRST_NAME) BETWEEN 7 AND 9;

----ONLY DISPLAY IF FIRST NAME CHARACTER COUNT NOT BETWEEN 5 -10
SELECT FIRST_NAME,LENGTH(FIRST_NAME)
FROM EMPLOYEES
WHERE LENGTH(FIRST_NAME) NOT BETWEEN 5 AND 10;

----ONLY DISPLAY IF FIRST NAME CHARACTER COUNT IS 2 OR 9 OR 11
SELECT FIRST_NAME,LENGTH(FIRST_NAME)
FROM EMPLOYEES
WHERE LENGTH(FIRST_NAME) IN (2,9,11);

--FIND PUT ALL FIRST_NAME THAT CONTAINS d OR D
SELECT FIRST_NAME,UPPER(FIRST_NAME)
FROM EMPLOYEES
--WHERE FIRST_NAME LIKE '%D%' OR FIRST_NAME LIKE '%d%'; Solution 1
WHERE UPPER(FIRST_NAME) LIKE '%D%';

--you can use single row anywhere
--including in select column list,condition, order by
SELECT FIRST_NAME
FROM EMPLOYEES
ORDER BY LENGTH(FIRST_NAME) DESC;

--NUMBER FUNCTIONS:
--ROUND(DECIMAL NUMBER HERE)-->Rounder number
--ROUND(DECIMAL NUMBER HERE,DIGIT YOU WANNA KEEP)
--              -->>ROUNDED NUMBER WITH DESIRED DIGIT
--

-- FIND OUT SALARY AND DAILY SALARY OF EMPLOYEE;
--KEEP 3 DIGIT AFTER
SELECT SALARY,
       ROUND(SALARY/30),
       ROUND(SALARY/30,3)
FROM EMPLOYEES;


--MULTI ROW FUNCTIONS \ GROUP FUNCTIONS \AGGREGATE FUNCTIONS
--COUNT MAX,MIN,SUM, AVG
--COUNT(*) MEANS COUNTS ALL

SELECT COUNT(*),COUNT(FIRST_NAME)
FROM EMPLOYEES;

--YOU CAN USE COUNT FUNCTION EITHER WITH * OR COLUMN NAME
--WHEN USED WITH * IT WIL JUST RETURN THE ROW COUNT
--WHEN USED WITH COLUMN NAME IT WILL RETURN NON-NULL ROW COUNT ONLY

--WE HAVE ONLY 35 EMPLOYEE WITH COMMISSION_PCT VALUE NOT NULL
--SO THE RESULT WILL BE 35
SELECT COUNT(COMMISSION_PCT)
FROM EMPLOYEES;
--GET THE EMPLOYEE COUNT FOR EMPLOYEES WITH DEPARTMENT_ID 90
SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID= 90;

--MAX
----FIND OUT THE MAX SALARY IN EMPLOYEES TABLE
SELECT MAX(SALARY)
FROM EMPLOYEES;

----FIND OUT THE MAX SALARY IN EMPLOYEES TABLE
--EXCLUDE THE SALARY 24000 NOT EQUAL SIGN!= OR <>
SELECT MAX(SALARY)
FROM EMPLOYEES
WHERE SALARY !=24000;


--MIN
---FIND OUT THE MIN SALARY IN EMPLOYEES TABLE
SELECT MIN(SALARY)
FROM EMPLOYEES;

---FIND OUT THE MAX SALARY IN EMPLOYEES TABLE
--EXCLUDE THE SALARY 21000 NOT EQUAL SIGN!= OR <>
SELECT MIN(SALARY)
FROM EMPLOYEES
WHERE SALARY <> 2100;

--SUM
--GET THE SUM PF ENTIRE EMPLOYEES SALARY
SELECT SUM(SALARY)
FROM EMPLOYEES;

--GET THE SUM PF ENTIRE EMPLOYEES SALARY FOR DEPARTMENT_ID 90
SELECT SUM(SALARY)
FROM EMPLOYEES
WHERE DEPARTMENT_ID= 90;

--AVG
--FIND OUT AVERAGE SALARY FOR ALL EMPLOYEES
SELECT AVG(SALARY),ROUND(AVG(SALARY))
FROM EMPLOYEES;










