--SUB QUERY: QUERY INSIDE ANOTHER QUERY


--FIND OUT MAX SALARY FROM EMPLOYEES
SELECT MAX(SALARY)
FROM EMPLOYEES;

SELECT FIRST_NAME
FROM EMPLOYEES
WHERE SALARY = 24000;

--WE HARD CODED THE VALUE OF 24000 WE GOT FROM FIRST QUERY INTO SECOND QUERY
--NOW JUST LIKE FUNCTION CALL WE CAN USE THIS QUERY
--AS A BLOCK OF QUERY THAT GENERATE MAX
SELECT FIRST_NAME
FROM EMPLOYEES
WHERE SALARY = (SELECT MAX(SALARY)
                FROM EMPLOYEES );

--FIND OUT THE NAME OF THE EMPLOYEE THAT MAKE LEAST SALARY
SELECT FIRST_NAME,SALARY
FROM EMPLOYEES
WHERE SALARY = (SELECT MIN(SALARY)
                FROM EMPLOYEES );
--FIND OUT THE NAME, SALARY OF THE EMPLOYEES THAT MAKE MORE THAN AVERAGE SALARY
SELECT AVG(SALARY) FROM EMPLOYEES;

SELECT FIRST_NAME,SALARY
FROM EMPLOYEES
WHERE SALARY > (SELECT AVG(SALARY)
                FROM EMPLOYEES );

--DISPLAY ALL EMPLOYEES IF SALARY IS NOT 24000
--AND FIND MAX SALARY
--ALSO KNOWN AS (AKA) SECOND MAX SALARY

SELECT SALARY
From EMPLOYEES
WHERE SALARY != (SELECT MAX(SALARY)FROM EMPLOYEES);


--WHAT ABOUT 3RD
SELECT MAX(SALARY)
FROM EMPLOYEES
WHERE SALARY < 17000; --FILTER ALL SALARY LESS THAN 2ND MAX

--JUST REPLACE THE 17000 WITH ABOVE QUERY
SELECT MAX(SALARY)
FROM EMPLOYEES
WHERE SALARY < (SELECT MAX(SALARY) FROM EMPLOYEES
                WHERE SALARY !=(SELECT MAX(SALARY) FROM EMPLOYEES));

--FIND OUT THE FIRST_NAME OF EMPLOYEES WHO WORKS IN EXECUTIVE DEPARTMENT

--FIND OUT THE DEPARTMENT_ID OF EXECUTIVE
SELECT DEPARTMENT_ID FROM DEPARTMENTS
WHERE DEPARTMENT_NAME = ' EXECUTIVE';

SELECT FIRST_NAME FROM EMPLOYEES
WHERE DEPARTMENT_ID = 90;

--NOW COMBINE THEM
SELECT FIRST_NAME FROM EMPLOYEES
WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM DEPARTMENTS
    WHERE DEPARTMENT_NAME = 'EXECUTIVE' );

--FIND OUT THE FIRST_NAME OF EMPLOYEES
--WHO WORKS IN EXECUTIVE AND ADMINISTRATIVE DEPARTMENT

--FIND OUT THE DEPARTMENT_ID OF EXECUTIVE
--AND ADMINISTEATION DEPARTMENT
SELECT DEPARTMENT_ID FROM DEPARTMENTS
WHERE DEPARTMENT_NAME IN ('Executive','Administration');


--FIND OUT THE FIRST_NAME OF EMPLOYEES
--WHO WORKS IN DEPARTMENT_ID 90 AND 10
SELECT FIRST_NAME FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (10,90);


--COMBINE THE RESULT

SELECT FIRST_NAME FROM EMPLOYEES
WHERE DEPARTMENT_ID IN(SELECT FIRST_NAME FROM EMPLOYEES
                       WHERE DEPARTMENT_ID IN (10,90));

---RESULT OF SUB QUERY CAN ALSO BE USED AS ENTIRE TABLE
--FOR EXAMPLE SELECT*FROM(SUB-QUERY GOES HERE)
SELECT FIRST_NAME,LAST_NAME, FIRST_NAME || LAST_NAME AS FULL_NAME
FROM EMPLOYEES
--WHERE FULL_NAME = 'EllenAbel' we can not use alias in condition
;

SELECT * FROM (SELECT FIRST_NAME, FIRST_NAME || LAST_NAME AS FULL_NAME
FROM EMPLOYEES)
WHERE FULL_NAME = 'EllenAbel';

--FIND OUT THE  EMPLOYEE COUNT OF THE DEPARTMENT WITH MOST EMPLOYEE
SELECT DEPARTMENT_ID,COUNT(*)AS Employee_Count
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID ;

--FIND OUT THE EMPLOYEE COUNT OF THE DEPARTMENT WITH MOST EMPLOYEE
SELECT MAX(EMPLOYEE_COUNT) FROM (SELECT DEPARTMENT_ID,COUNT(*)AS Employee_Count
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID);

--DENSE_RANK FUNCTION THAT FAL INTO CATEGORY OF ANALYTICAL FUNCTIONS
--DENSE_RANK() OVER (ORDER BY SALARY DESK)
SELECT FIRST_NAME,SALARY,DENSE_RANK() over (ORDER BY SALARY DESC ) AS SALARY_RANK
FROM EMPLOYEES;

--NOW WE CAN SEE THIS WHOLE RESULT OF ABOVE QUERY AS A TABLE
--SELECT FROM THIS "TABLE" AND FILTER THE RESULT
SELECT*
FROM (SELECT FIRST_NAME,SALARY,DENSE_RANK() over (ORDER BY SALARY DESC ) AS SALARY_RANK
      FROM EMPLOYEES)
WHERE SALARY_RANK = 3;

--SELECT *FROM EMP_SALARY_RANK
--WHERE SALARY_RANK =4;

----100,34,88,90,55
----  5   1  3  4 2








